# Generated by Django 6.0 on 2025-12-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Açıklama'),
        ),
    ]
