# Generated by Django 6.0 on 2025-12-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_customuser_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Biyografi'),
        ),
    ]
