# Generated by Django 6.0 on 2025-12-29 00:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnail/', verbose_name='Kapak Görseli')),
                ('meta_title', models.CharField(max_length=60, verbose_name='Meta Başlık')),
                ('title', models.CharField(max_length=70, verbose_name='Başlık')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Meta Açıklama')),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True, verbose_name='URL')),
                ('page_css', models.TextField(blank=True, verbose_name='Özel CSS')),
                ('content', models.TextField(help_text='Makale içeriğini buraya girin. Görselleri, başlıkları (H2, H3) editör araçlarıyla ekleyin.', validators=[django.core.validators.MinLengthValidator(limit_value=300, message='SEO standardı gereği içerik en az 300 karakter olmalıdır.')], verbose_name='İçerik Gövdesi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='Blog.tag', verbose_name='Etiketler')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
