# Generated by Django 6.0 on 2025-12-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_author_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_alt',
            field=models.CharField(default='Thumbnail Görseli', max_length=125, verbose_name='Kapak Görseli Açıklaması'),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_owner',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Thumbnail Sahibi'),
        ),
    ]
