# Generated by Django 6.0 on 2025-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Anahtar (Key)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='HTML/Yazı İçeriği')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dynamic_contents/', verbose_name='Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dinamik İçerik',
                'verbose_name_plural': 'Dinamik İçerikler',
            },
        ),
    ]
